name: bonsu
favicon: null
layout_spectrum: 0.28523090947419405
typography_spectrum: 0.5459935257676989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.27799064898863435
  lightness: 0.21289442107081413
  saturation: 0.49445106112398207
  rhythmicContrast: 0.9163650623522699
purpose: []
